### ISSUE TITLE
A lot of drafted players don't have their NBA stats?

### ISSUE THREAD

**Issue by anhqle** [LaDilettante/cs316_nba#2]
You guys can see these players in [my Jupyter notebook](https://github.com/LaDilettante/cs316_nba/blob/a5f257fcd04ec2233608f56dd4efd9251dddf11f/code/Predictive%20model%20for%20NBA%20performance.ipynb), cell 46.

Any idea why this happens? @vidurmalhotra22 @ab546 ?

**Comment by vidurmalhotra22** [comment]
So a lot of people drafted never see playing time because they are not good enough. That could account for it. Just because a player is drafted does not necessarily mean they will play in the NBA.

**Comment by anhqle** [comment]
Yeah, that's right. Many don't get to play due to injuries or being moved to D-League as well. Thanks!

I also missed a few people by joining based on name, team and year. It turns out that some people get drafted for a certain team in a certain year, but then play for another team in another year. So joining on name only is a better idea.
